org: sidd34po
app: lamda
service: servicetwo
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    restApiId:
      ${param:SharedGW-restApiId}
    restApiRootResourceId:
      ${param:SharedGW-rootResourceId}

functions:
  function1:
    handler: index.handler
    events:
      - http:
          path: servicetwo/list
          method: get
