plugins:
  - serverless-export-env

org: sidd34po
app: lamda
service: serviceone
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    restApiId: ${self:custom.sharedGWRestApiId}
    restApiRootResourceId: ${self:custom.sharedGWRootResourceId}

functions:
  handler1:
    handler: index.handler1
    events:
      - http:
          path: serviceone/list1
          method: get
  handler2:
    handler: index.handler2
    events:
      - http:
          path: serviceone/list2
          method: get
  handler3:
    handler: index.handler3
    events:
      - http:
          path: serviceone/list3
          method: get

custom:
  sharedGWRestApiId:
    'Fn::ImportValue': SharedGW-restApiId
  sharedGWRootResourceId:
    'Fn::ImportValue': SharedGW-rootResourceId