plugins:
  - serverless-export-env

org: sidd34po
app: lamda
service: serviceone
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    restApiId: ${self:custom.sharedGWRestApiId}
    restApiRootResourceId: ${self:custom.sharedGWRootResourceId}

functions:
  function1:
    handler: index.handler
    events:
      - http:
          path: serviceone/list
          method: get

custom:
  sharedGWRestApiId:
    'Fn::ImportValue': SharedGW-restApiId
  sharedGWRootResourceId:
    'Fn::ImportValue': SharedGW-rootResourceId